-- Audit fields are database-owned. @app_actor_id is set on the transaction connection.
CREATE TRIGGER files_audit_bi BEFORE INSERT ON files FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER files_audit_bu BEFORE UPDATE ON files FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER files_audit_bd BEFORE DELETE ON files FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER identity_service_accounts_audit_bi BEFORE INSERT ON identity_service_accounts FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER identity_service_accounts_audit_bu BEFORE UPDATE ON identity_service_accounts FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER identity_service_accounts_audit_bd BEFORE DELETE ON identity_service_accounts FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER identity_sessions_audit_bi BEFORE INSERT ON identity_sessions FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER identity_sessions_audit_bu BEFORE UPDATE ON identity_sessions FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER identity_sessions_audit_bd BEFORE DELETE ON identity_sessions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER identity_user_credentials_audit_bi BEFORE INSERT ON identity_user_credentials FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER identity_user_credentials_audit_bu BEFORE UPDATE ON identity_user_credentials FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER identity_user_credentials_audit_bd BEFORE DELETE ON identity_user_credentials FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER identity_users_audit_bi BEFORE INSERT ON identity_users FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER identity_users_audit_bu BEFORE UPDATE ON identity_users FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER identity_users_audit_bd BEFORE DELETE ON identity_users FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER menus_audit_bi BEFORE INSERT ON menus FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER menus_audit_bu BEFORE UPDATE ON menus FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER menus_audit_bd BEFORE DELETE ON menus FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER operation_logs_audit_bi BEFORE INSERT ON operation_logs FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER operation_logs_audit_bu BEFORE UPDATE ON operation_logs FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER operation_logs_audit_bd BEFORE DELETE ON operation_logs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER permissions_audit_bi BEFORE INSERT ON permissions FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER permissions_audit_bu BEFORE UPDATE ON permissions FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER permissions_audit_bd BEFORE DELETE ON permissions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER platform_configs_audit_bi BEFORE INSERT ON platform_configs FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER platform_configs_audit_bu BEFORE UPDATE ON platform_configs FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER platform_configs_audit_bd BEFORE DELETE ON platform_configs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER route_definitions_audit_bi BEFORE INSERT ON route_definitions FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER route_definitions_audit_bu BEFORE UPDATE ON route_definitions FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER route_definitions_audit_bd BEFORE DELETE ON route_definitions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER route_policy_definitions_audit_bi BEFORE INSERT ON route_policy_definitions FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER route_policy_definitions_audit_bu BEFORE UPDATE ON route_policy_definitions FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER route_policy_definitions_audit_bd BEFORE DELETE ON route_policy_definitions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER route_policy_permission_refs_audit_bi BEFORE INSERT ON route_policy_permission_refs FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER route_policy_permission_refs_audit_bu BEFORE UPDATE ON route_policy_permission_refs FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER route_policy_permission_refs_audit_bd BEFORE DELETE ON route_policy_permission_refs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER security_logs_audit_bi BEFORE INSERT ON security_logs FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER security_logs_audit_bu BEFORE UPDATE ON security_logs FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER security_logs_audit_bd BEFORE DELETE ON security_logs FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER tenant_administrators_audit_bi BEFORE INSERT ON tenant_administrators FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER tenant_administrators_audit_bu BEFORE UPDATE ON tenant_administrators FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER tenant_administrators_audit_bd BEFORE DELETE ON tenant_administrators FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER tenant_department_members_audit_bi BEFORE INSERT ON tenant_department_members FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER tenant_department_members_audit_bu BEFORE UPDATE ON tenant_department_members FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER tenant_department_members_audit_bd BEFORE DELETE ON tenant_department_members FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER tenant_departments_audit_bi BEFORE INSERT ON tenant_departments FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER tenant_departments_audit_bu BEFORE UPDATE ON tenant_departments FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER tenant_departments_audit_bd BEFORE DELETE ON tenant_departments FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER tenant_member_roles_audit_bi BEFORE INSERT ON tenant_member_roles FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER tenant_member_roles_audit_bu BEFORE UPDATE ON tenant_member_roles FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER tenant_member_roles_audit_bd BEFORE DELETE ON tenant_member_roles FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER tenant_memberships_audit_bi BEFORE INSERT ON tenant_memberships FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER tenant_memberships_audit_bu BEFORE UPDATE ON tenant_memberships FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER tenant_memberships_audit_bd BEFORE DELETE ON tenant_memberships FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER tenant_permission_grants_audit_bi BEFORE INSERT ON tenant_permission_grants FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER tenant_permission_grants_audit_bu BEFORE UPDATE ON tenant_permission_grants FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER tenant_permission_grants_audit_bd BEFORE DELETE ON tenant_permission_grants FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER tenant_role_permissions_audit_bi BEFORE INSERT ON tenant_role_permissions FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER tenant_role_permissions_audit_bu BEFORE UPDATE ON tenant_role_permissions FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER tenant_role_permissions_audit_bd BEFORE DELETE ON tenant_role_permissions FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER tenant_roles_audit_bi BEFORE INSERT ON tenant_roles FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER tenant_roles_audit_bu BEFORE UPDATE ON tenant_roles FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER tenant_roles_audit_bd BEFORE DELETE ON tenant_roles FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';

CREATE TRIGGER tenants_audit_bi BEFORE INSERT ON tenants FOR EACH ROW SET NEW.created_at = CURRENT_TIMESTAMP(6), NEW.created_by = NULLIF(TRIM(@app_actor_id), ''), NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL ELSE NULLIF(TRIM(@app_actor_id), '') END;
CREATE TRIGGER tenants_audit_bu BEFORE UPDATE ON tenants FOR EACH ROW SET NEW.created_at = OLD.created_at, NEW.created_by = OLD.created_by, NEW.updated_at = CURRENT_TIMESTAMP(6), NEW.updated_by = NULLIF(TRIM(@app_actor_id), ''), NEW.version = OLD.version + 1, NEW.deleted_by = CASE WHEN NEW.deleted_at IS NULL THEN NULL WHEN OLD.deleted_at IS NULL THEN NULLIF(TRIM(@app_actor_id), '') ELSE OLD.deleted_by END;
CREATE TRIGGER tenants_audit_bd BEFORE DELETE ON tenants FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'physical delete is forbidden';


