CREATE TABLE operation_logs (
    id varchar(64) NOT NULL PRIMARY KEY,
    tenant_id text NOT NULL,
    actor_id text NOT NULL,
    actor_type text NOT NULL,
    application_id text NOT NULL,
    source text NOT NULL,
    operation text NOT NULL,
    resource_type text NOT NULL,
    resource_id text NOT NULL,
    protocol text NOT NULL,
    method text NOT NULL,
    route text NOT NULL,
    request_payload text NOT NULL,
    duration_ms bigint NOT NULL,
    succeeded boolean NOT NULL,
    error_code text NOT NULL,
    error_message text NOT NULL,
    request_id text NOT NULL,
    trace_id text NOT NULL,
    client_ip text NOT NULL,
    user_agent text NOT NULL,
    extension json NOT NULL,
    occurred_at timestamp(6) NOT NULL,
    created_at timestamp(6) NOT NULL,
    created_by text NOT NULL,
    updated_at timestamp(6) NOT NULL,
    updated_by text NOT NULL,
    version bigint NOT NULL,
    deleted_at timestamp(6) NULL,
    deleted_by text NULL,
    KEY operation_logs_tenant_occurred_idx (tenant_id(128), occurred_at, id),
    KEY operation_logs_actor_occurred_idx (actor_id(128), occurred_at),
    KEY operation_logs_tenant_operation_idx (tenant_id(96), operation(96), occurred_at),
    KEY operation_logs_tenant_resource_idx (tenant_id(64), resource_type(64), resource_id(64), occurred_at),
    KEY operation_logs_tenant_application_idx (tenant_id(96), application_id(96), occurred_at),
    KEY operation_logs_request_id_idx (request_id(128))
);
