CREATE TABLE security_logs (
    id varchar(64) NOT NULL PRIMARY KEY,
    tenant_id text NOT NULL,
    actor_id text NOT NULL,
    actor_type text NOT NULL,
    subject_id text NOT NULL,
    subject_type text NOT NULL,
    event_type text NOT NULL,
    succeeded boolean NOT NULL,
    reason text NOT NULL,
    error_code text NOT NULL,
    error_message text NOT NULL,
    identifier_hash text NOT NULL,
    token_id_hash text NOT NULL,
    session_id text NOT NULL,
    request_id text NOT NULL,
    trace_id text NOT NULL,
    client_ip text NOT NULL,
    user_agent text NOT NULL,
    metadata json NOT NULL,
    occurred_at timestamp(6) NOT NULL,
    created_at timestamp(6) NOT NULL,
    created_by text NOT NULL,
    updated_at timestamp(6) NOT NULL,
    updated_by text NOT NULL,
    version bigint NOT NULL,
    deleted_at timestamp(6) NULL,
    deleted_by text NULL,
    KEY security_logs_subject_occurred_idx (subject_id(128), occurred_at),
    KEY security_logs_identifier_occurred_idx (identifier_hash(64), occurred_at),
    KEY security_logs_event_occurred_idx (event_type(64), occurred_at),
    KEY security_logs_tenant_occurred_idx (tenant_id(64), occurred_at, id),
    KEY security_logs_tenant_event_occurred_idx (tenant_id(64), event_type(64), occurred_at),
    KEY security_logs_tenant_subject_occurred_idx (tenant_id(64), subject_id(128), occurred_at),
    KEY security_logs_request_idx (request_id(128))
);
