app:
  env: compose
log:
  level: debug
  file: /app/logs/app.log
swagger:
  enabled: true
database:
  name: go_api_template_db
  schema: go_api_template
grpc:
  reflection_enabled: true
cron:
  enabled: true
