CREATE TABLE applications (id text PRIMARY KEY,code text NOT NULL,name text NOT NULL,description text NOT NULL DEFAULT '',icon text NOT NULL DEFAULT '',home_path text NOT NULL DEFAULT '',status text NOT NULL CHECK(status IN('active','disabled')),sort_order bigint NOT NULL DEFAULT 0,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL,created_by text NOT NULL,updated_at timestamptz NOT NULL,updated_by text NOT NULL,version bigint NOT NULL CHECK(version>0),deleted_at timestamptz,deleted_by text);
CREATE UNIQUE INDEX applications_code_unique ON applications(lower(code)) WHERE deleted_at IS NULL;
CREATE INDEX applications_page_idx ON applications(status,sort_order,id) WHERE deleted_at IS NULL;
SELECT app_enable_audit('applications');
CREATE TABLE navigations (id text PRIMARY KEY,application_id text NOT NULL REFERENCES applications(id),parent_id text REFERENCES navigations(id),navigation_key text NOT NULL,name text NOT NULL,navigation_type text NOT NULL CHECK(navigation_type IN('directory','menu')),route_path text NOT NULL DEFAULT '',component text NOT NULL DEFAULT '',icon text NOT NULL DEFAULT '',resource text NOT NULL DEFAULT '',action text NOT NULL DEFAULT '',visible boolean NOT NULL DEFAULT true,status text NOT NULL CHECK(status IN('active','disabled')),sort_order bigint NOT NULL DEFAULT 0,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL,created_by text NOT NULL,updated_at timestamptz NOT NULL,updated_by text NOT NULL,version bigint NOT NULL CHECK(version>0),deleted_at timestamptz,deleted_by text,CHECK((navigation_type='directory' AND component='' AND resource='' AND action='') OR (navigation_type='menu' AND route_path<>'' AND component<>'' AND resource<>'' AND action<>'')));
CREATE UNIQUE INDEX navigations_key_unique ON navigations(application_id,lower(navigation_key)) WHERE deleted_at IS NULL;
CREATE INDEX navigations_tree_idx ON navigations(application_id,parent_id,sort_order,id) WHERE deleted_at IS NULL;
CREATE INDEX navigations_target_idx ON navigations(resource,action) WHERE deleted_at IS NULL AND resource<>'';
SELECT app_enable_audit('navigations');
